apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mongo-client-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{ .Values.allowedPodLabel.key }}: {{ .Values.allowedPodLabel.value }}
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.targetIp }}/32
      ports:
        - protocol: TCP
          port: 27017
    - to:
        - ipBlock:
            cidr: {{ .Values.targetIp }}/32
      ports:
        - protocol: ICMP