apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}  # Applies to all pods
  policyTypes:
    - Egress
  egress: []  # No egress alloweddeny-all-egress.yaml