name: Deploy VM from VM/Terraform

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: VM/Terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID"  -var "mongodb_admin_password=$MONGODB_ADMIN_PASSWORD"
  
      - name: Terraform Apply
        run: terraform apply -auto-approve -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID" -var "mongodb_admin_password=$MONGODB_ADMIN_PASSWORD"

      - name: Save private SSH key to file
        run: |
          terraform output -raw ssh_private_key > dbserver_key.pem
          chmod 600 dbserver_key.pem
        working-directory: VM/Terraform

      - name: Upload SSH private key as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-key
          path: VM/Terraform/dbserver_key.pem
