name: Deploy Ubuntu DB Server

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  MONGODB_ADMIN_PASSWORD: ${{ secrets.MONGODB_ADMIN_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: VM/Terraform

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve \
            -var "client_id=$ARM_CLIENT_ID" \
            -var "client_secret=$ARM_CLIENT_SECRET" \
            -var "tenant_id=$ARM_TENANT_ID" \
            -var "subscription_id=$ARM_SUBSCRIPTION_ID" \
            -var "mongodb_admin_password=$MONGODB_ADMIN_PASSWORD"
        working-directory: AKS/Terraform

      - name: Save private SSH key to file
        run: |
          terraform output -raw ssh_private_key > dbserver_key.pem
          chmod 600 dbserver_key.pem
        working-directory: AKS/Terraform

      - name: Upload SSH private key as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ssh-key
          path: AKS/Terraform/dbserver_key.pem
