name: Deploy Storage From Storage/Terraform

on:
  workflow_dispatch:
  # Optional: Trigger only when files in AKS/Terraform/ change
  # push:
  #   paths:
  #     - 'Storage/Terraform/**'

jobs:
  terraform:
    name: Deploy Storage From Storage/Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Storage/Terraform
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
      STORAGE_KEY: ${{ secrets.STORAGE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var "client_id=$ARM_CLIENT_ID" -var "client_secret=$ARM_CLIENT_SECRET" -var "tenant_id=$ARM_TENANT_ID" -var "subscription_id=$ARM_SUBSCRIPTION_ID
