name: Setup MongoDB Backup CronJob

on:
  workflow_dispatch:
  # Optional: Trigger only when files in AKS/Terraform/ change
  # push:
  #   paths:
  #     - 'Storage/Backup/**'

jobs:
  setup-cron:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Storage/Backup

    env:
      VM_SSH_USER: ${{ secrets.VM_SSH_USER }}
      VM_SSH_HOST: ${{ secrets.VM_SSH_HOST }}
      VM_SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_PRIVATE_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - uses: actions/checkout@v4

      - name: Copy backup script to VM
        run: |
          echo "$VM_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -o StrictHostKeyChecking=no -i private_key.pem backup-mongo.sh $VM_SSH_USER@$VM_SSH_HOST:/home/$VM_SSH_USER/backup-mongo.sh

      - name: Setup cronjob on VM
        run: |
          echo "$VM_SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $VM_SSH_USER@$VM_SSH_HOST << EOF
            chmod +x /home/$VM_SSH_USER/backup-mongo.sh

            (crontab -l 2>/dev/null; echo "0 * * * * MONGO_URI='$MONGO_URI' /home/$VM_SSH_USER/backup-mongo.sh >> /home/$VM_SSH_USER/backup-mongo.log 2>&1") | crontab -
          EOF
